/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPaginasRouteImport } from './routes/_authenticated/admin.paginas'
import { Route as AuthenticatedAdminMidiaRouteImport } from './routes/_authenticated/admin.midia'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminFormulariosRouteImport } from './routes/_authenticated/admin.formularios'
import { Route as AuthenticatedAdminFeatureFlagsRouteImport } from './routes/_authenticated/admin.feature-flags'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminSeoIndexRouteImport } from './routes/_authenticated/admin.seo.index'
import { Route as AuthenticatedAdminProdutosIndexRouteImport } from './routes/_authenticated/admin.produtos.index'
import { Route as AuthenticatedAdminPaginasIndexRouteImport } from './routes/_authenticated/admin.paginas.index'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated/admin.produtos.$id'
import { Route as AuthenticatedAdminPaginasIdRouteImport } from './routes/_authenticated/admin.paginas.$id'
import { Route as AuthenticatedAdminSeoResourceTypeResourceIdRouteImport } from './routes/_authenticated/admin.seo.$resourceType.$resourceId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaginasRoute =
  AuthenticatedAdminPaginasRouteImport.update({
    id: '/paginas',
    path: '/paginas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMidiaRoute = AuthenticatedAdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFormulariosRoute =
  AuthenticatedAdminFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeatureFlagsRoute =
  AuthenticatedAdminFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoIndexRoute =
  AuthenticatedAdminSeoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSeoRoute,
  } as any)
const AuthenticatedAdminProdutosIndexRoute =
  AuthenticatedAdminProdutosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)
const AuthenticatedAdminPaginasIndexRoute =
  AuthenticatedAdminPaginasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPaginasRoute,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)
const AuthenticatedAdminPaginasIdRoute =
  AuthenticatedAdminPaginasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPaginasRoute,
  } as any)
const AuthenticatedAdminSeoResourceTypeResourceIdRoute =
  AuthenticatedAdminSeoResourceTypeResourceIdRouteImport.update({
    id: '/$resourceType/$resourceId',
    path: '/$resourceType/$resourceId',
    getParentRoute: () => AuthenticatedAdminSeoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRouteWithChildren
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/seo': typeof AuthenticatedAdminSeoRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/paginas/': typeof AuthenticatedAdminPaginasIndexRoute
  '/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
  '/admin/seo/': typeof AuthenticatedAdminSeoIndexRoute
  '/admin/seo/$resourceType/$resourceId': typeof AuthenticatedAdminSeoResourceTypeResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasIndexRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosIndexRoute
  '/admin/seo': typeof AuthenticatedAdminSeoIndexRoute
  '/admin/seo/$resourceType/$resourceId': typeof AuthenticatedAdminSeoResourceTypeResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/_authenticated/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/_authenticated/admin/paginas': typeof AuthenticatedAdminPaginasRouteWithChildren
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/_authenticated/admin/paginas/': typeof AuthenticatedAdminPaginasIndexRoute
  '/_authenticated/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
  '/_authenticated/admin/seo/': typeof AuthenticatedAdminSeoIndexRoute
  '/_authenticated/admin/seo/$resourceType/$resourceId': typeof AuthenticatedAdminSeoResourceTypeResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/cookies'
    | '/portfolio'
    | '/privacidade'
    | '/produtos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin'
    | '/blog/$slug'
    | '/admin/auditoria'
    | '/admin/blog'
    | '/admin/configuracoes'
    | '/admin/feature-flags'
    | '/admin/formularios'
    | '/admin/leads'
    | '/admin/midia'
    | '/admin/paginas'
    | '/admin/produtos'
    | '/admin/seo'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/paginas/$id'
    | '/admin/produtos/$id'
    | '/admin/paginas/'
    | '/admin/produtos/'
    | '/admin/seo/'
    | '/admin/seo/$resourceType/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/cookies'
    | '/portfolio'
    | '/privacidade'
    | '/produtos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/admin/auditoria'
    | '/admin/blog'
    | '/admin/configuracoes'
    | '/admin/feature-flags'
    | '/admin/formularios'
    | '/admin/leads'
    | '/admin/midia'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/paginas/$id'
    | '/admin/produtos/$id'
    | '/admin/paginas'
    | '/admin/produtos'
    | '/admin/seo'
    | '/admin/seo/$resourceType/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/cookies'
    | '/portfolio'
    | '/privacidade'
    | '/produtos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/feature-flags'
    | '/_authenticated/admin/formularios'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/midia'
    | '/_authenticated/admin/paginas'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/paginas/$id'
    | '/_authenticated/admin/produtos/$id'
    | '/_authenticated/admin/paginas/'
    | '/_authenticated/admin/produtos/'
    | '/_authenticated/admin/seo/'
    | '/_authenticated/admin/seo/$resourceType/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paginas': {
      id: '/_authenticated/admin/paginas'
      path: '/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AuthenticatedAdminPaginasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/midia': {
      id: '/_authenticated/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AuthenticatedAdminMidiaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formularios': {
      id: '/_authenticated/admin/formularios'
      path: '/formularios'
      fullPath: '/admin/formularios'
      preLoaderRoute: typeof AuthenticatedAdminFormulariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feature-flags': {
      id: '/_authenticated/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AuthenticatedAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo/': {
      id: '/_authenticated/admin/seo/'
      path: '/'
      fullPath: '/admin/seo/'
      preLoaderRoute: typeof AuthenticatedAdminSeoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSeoRoute
    }
    '/_authenticated/admin/produtos/': {
      id: '/_authenticated/admin/produtos/'
      path: '/'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
    '/_authenticated/admin/paginas/': {
      id: '/_authenticated/admin/paginas/'
      path: '/'
      fullPath: '/admin/paginas/'
      preLoaderRoute: typeof AuthenticatedAdminPaginasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPaginasRoute
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
    '/_authenticated/admin/paginas/$id': {
      id: '/_authenticated/admin/paginas/$id'
      path: '/$id'
      fullPath: '/admin/paginas/$id'
      preLoaderRoute: typeof AuthenticatedAdminPaginasIdRouteImport
      parentRoute: typeof AuthenticatedAdminPaginasRoute
    }
    '/_authenticated/admin/seo/$resourceType/$resourceId': {
      id: '/_authenticated/admin/seo/$resourceType/$resourceId'
      path: '/$resourceType/$resourceId'
      fullPath: '/admin/seo/$resourceType/$resourceId'
      preLoaderRoute: typeof AuthenticatedAdminSeoResourceTypeResourceIdRouteImport
      parentRoute: typeof AuthenticatedAdminSeoRoute
    }
  }
}

interface AuthenticatedAdminPaginasRouteChildren {
  AuthenticatedAdminPaginasIdRoute: typeof AuthenticatedAdminPaginasIdRoute
  AuthenticatedAdminPaginasIndexRoute: typeof AuthenticatedAdminPaginasIndexRoute
}

const AuthenticatedAdminPaginasRouteChildren: AuthenticatedAdminPaginasRouteChildren =
  {
    AuthenticatedAdminPaginasIdRoute: AuthenticatedAdminPaginasIdRoute,
    AuthenticatedAdminPaginasIndexRoute: AuthenticatedAdminPaginasIndexRoute,
  }

const AuthenticatedAdminPaginasRouteWithChildren =
  AuthenticatedAdminPaginasRoute._addFileChildren(
    AuthenticatedAdminPaginasRouteChildren,
  )

interface AuthenticatedAdminProdutosRouteChildren {
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
  AuthenticatedAdminProdutosIndexRoute: typeof AuthenticatedAdminProdutosIndexRoute
}

const AuthenticatedAdminProdutosRouteChildren: AuthenticatedAdminProdutosRouteChildren =
  {
    AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
    AuthenticatedAdminProdutosIndexRoute: AuthenticatedAdminProdutosIndexRoute,
  }

const AuthenticatedAdminProdutosRouteWithChildren =
  AuthenticatedAdminProdutosRoute._addFileChildren(
    AuthenticatedAdminProdutosRouteChildren,
  )

interface AuthenticatedAdminSeoRouteChildren {
  AuthenticatedAdminSeoIndexRoute: typeof AuthenticatedAdminSeoIndexRoute
  AuthenticatedAdminSeoResourceTypeResourceIdRoute: typeof AuthenticatedAdminSeoResourceTypeResourceIdRoute
}

const AuthenticatedAdminSeoRouteChildren: AuthenticatedAdminSeoRouteChildren = {
  AuthenticatedAdminSeoIndexRoute: AuthenticatedAdminSeoIndexRoute,
  AuthenticatedAdminSeoResourceTypeResourceIdRoute:
    AuthenticatedAdminSeoResourceTypeResourceIdRoute,
}

const AuthenticatedAdminSeoRouteWithChildren =
  AuthenticatedAdminSeoRoute._addFileChildren(
    AuthenticatedAdminSeoRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminFeatureFlagsRoute: typeof AuthenticatedAdminFeatureFlagsRoute
  AuthenticatedAdminFormulariosRoute: typeof AuthenticatedAdminFormulariosRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMidiaRoute: typeof AuthenticatedAdminMidiaRoute
  AuthenticatedAdminPaginasRoute: typeof AuthenticatedAdminPaginasRouteWithChildren
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRouteWithChildren
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminFeatureFlagsRoute: AuthenticatedAdminFeatureFlagsRoute,
  AuthenticatedAdminFormulariosRoute: AuthenticatedAdminFormulariosRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMidiaRoute: AuthenticatedAdminMidiaRoute,
  AuthenticatedAdminPaginasRoute: AuthenticatedAdminPaginasRouteWithChildren,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRouteWithChildren,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRouteWithChildren,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
